version: '3'

services:
  db:
    image: mariadb:10.4
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: bank
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: my-secret-pw
    restart: unless-stopped

  app:
    build:
      context: .
    command: npm run start
    ports:
      - 81:80
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PW: test
      DB_DB: bank
      PORT: 80
    restart: unless-stopped
